### ISSUE TITLE
Login with wrong password ios crashing

### ISSUE THREAD

**Issue by midhilaj-com-06** [scientifichackers/flutter_cognito_plugin#31]
Thread 26: Fatal error: Unexpectedly found nil while unwrapping an Optional value

Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/user/FlutterHome/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_aws_amplify_cognito-1.0.0+7/ios/Classes/SwiftFlutterAwsAmplifyCognito.swift, line 275

https://github.com/jonsaw/amazon-cognito-identity-dart

**Comment by devxpy** [comment]
Wrong plugin, see [flutter_aws_amplify_cognito](https://github.com/agnostech/flutter_amplify/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
